version: '3'
services:
  server:
    image: llmctf/2016f-web-seizurecipher
    ports:
      - 9000:9000
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io

networks:
  ctfnet:
    external: true