version: '3'
services:
  server:
    image: llmctf/2016q-pwn-tutorial
    ports:
      - 4242:4242
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true