version: '3'
services:
  server:
    image: llmctf/2016q-msc-coinslot
    ports:
      - 8000:8000
    networks:
      ctfnet:
        aliases:
          - misc.chal.csaw.io

networks:
  ctfnet:
    external: true