version: '3'
services:
  server:
    image: llmctf/2014f-msc-pps
    ports:
      - 5665:5665
    networks:
      ctfnet:
        aliases:
          - misc.chal.csaw.io

networks:
  ctfnet:
    external: true