version: '3'
services:
  server:
    image: llmctf/2015q-web-throwback
    ports:
      - 4000:4000
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io

networks:
  ctfnet:
    external: true