version: '3'
services:
  server:
    image: llmctf/2014q-pwn-ish
    ports:
      - 9988:9988
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true