version: '3'
services:
  server:
    image: llmctf/2015q-pwn-autobots
    ports:
      - 9000:9000
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true