version: '3'
services:
  server:
    image: llmctf/2016q-cry-sleeping_guard
    ports:
      - 8000:8000
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io

networks:
  ctfnet:
    external: true