version: '3'
services:
  server:
    image: llmctf/2015f-pwn-hipster
    ports:
      - 8025:8025
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true