version: '3'
services:
  server:
    image: llmctf/2014q-web-silkgoat
    ports:
      - 5000:5000
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io

networks:
  ctfnet:
    external: true