version: '3'
services:
  server:
    image: llmctf/2015q-pwn-meme-shop
    ports:
      - 8000:8000
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true